## **Advertisement Sale prediction from an existing customer using LOGISTIC REGRESSION**

In [ ]:
# importing libraries
import pandas as pd #used for loading dataset
#import numpy as np to perform array

In [ ]:
#uploaded data from google collab
from google.colab import files
uploaded = files.upload()

Saving DigitalAd_dataset23.csv to DigitalAd_dataset23.csv


In [ ]:
#load dataset
dataset = pd.read_csv('DigitalAd_dataset23.csv')
print(dataset)

      salary  Age  status
0      10000   16       0
1      10000   16       0
2      10000   16       0
3      10000   16       0
4      10000   16       0
...      ...  ...     ...
9686  100000   70       1
9687  100000   70       1
9688  100000   70       1
9689  100000   70       1
9690  100000   70       1

[9691 rows x 3 columns]


In [ ]:
#summarize of data
print(dataset.shape)
print(dataset.head(5))
#head means starting 5 and
#tail means last 5 (5 is number of output we want)

(9691, 3)
   salary  Age  status
0   10000   16       0
1   10000   16       0
2   10000   16       0
3   10000   16       0
4   10000   16       0


In [ ]:
#segregagtion
X = dataset.iloc[:,:-1].values
X

array([[ 10000,     16],
       [ 10000,     16],
       [ 10000,     16],
       ...,
       [100000,     70],
       [100000,     70],
       [100000,     70]])

In [ ]:
#segregagtion
Y = dataset.iloc[:,-1].values
Y

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
#spliting and training dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[ 1.76267948 -0.05985214]
 [-1.36368684  0.50804   ]
 [-0.32156474  0.69733738]
 ...
 [ 1.76267948  1.58072516]
 [ 0.30370853  0.57113913]
 [-0.32156474  1.39142778]]


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
#predicting
age = int(input("Enter Customer Age:"))
sal = int(input("Enter Customers Salary:"))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("cutsomer will buy ")
else:
  print("Will not Buy ")

Enter Customer Age:50
Enter Customers Salary:10000
[0]
Will not Buy 
